// ⚠️⚠️⚠️⚠️⚠️
// Edit these files in https://github.com/framer/FramerCodeComponents
// ⚠️⚠️⚠️⚠️⚠️
import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{DotLottieReact}from"@lottiefiles/dotlottie-react";import{addPropertyControls,ControlType,RenderTarget}from"framer";import{useEffect,useRef,useState}from"react";import LottieControls from"https://framerusercontent.com/modules/VdEWJdgFIKHb8shmJI6x/JMuQueQTE5Pf7GsLqM4w/LottieControls.js";const placeholderUrl="https://lottie.host/d826e0a7-b7e8-4072-8afe-c943ed2dd2ca/DpX3m5yT5Z.lottie";const DotLottieReactPlayer=DotLottieReact;/**
 * DOT LOTTIE
 *
 * @framerIntrinsicWidth 200
 * @framerIntrinsicHeight 200
 * @framerDisableUnlink
 *
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 */export default function DotLottie(props){/* Checks */const isCanvas=RenderTarget.current()===RenderTarget.canvas;const[dotLottie,setDotLottie]=useState(null);const mode=props.direction==="-1"?"reverse":"forward";/* File or URL */let src;switch(props.srcType){case"url":src=props.srcUrl;break;case"file":src=props.srcFile;break;default:src=placeholderUrl;break;}/* Progress */const[isReady,setIsReady]=useState(false);/* For canvas states */useEffect(()=>{setIsReady(false);if(!dotLottie)return;const handleLoad=()=>setIsReady(true);if(dotLottie.isLoaded)setIsReady(true);dotLottie.addEventListener("load",handleLoad);return()=>{dotLottie.removeEventListener("load",handleLoad);};},[dotLottie,src]);useEffect(()=>{if(!isReady||!dotLottie||!dotLottie.totalFrames)return;const nextProgress=props.progress??0;dotLottie.setFrame(nextProgress/100*dotLottie.totalFrames);},[dotLottie,isReady,props.progress,src]);/* For component variant support */const lastVariant=useRef();useEffect(()=>{if(isCanvas)return;if(lastVariant.current!==props.autoplay){if(!dotLottie)return;if(props.autoplay===true){dotLottie.play();}if(props.autoplay===false){dotLottie.pause();}}lastVariant.current=props.autoplay;},[dotLottie,isCanvas,props.autoplay]);return /*#__PURE__*/_jsxs("div",{style:{...props.style,position:"relative",width:"100%",height:"100%",display:"flex",flexDirection:"column"},children:[/*#__PURE__*/_jsx("div",{style:{position:"relative",width:"100%",flex:1,minHeight:0},children:/*#__PURE__*/_jsx(DotLottieReactPlayer,{src:src,autoplay:!isCanvas&&!props.hover&&props.autoplay,loop:props.loop,mode:mode,playOnHover:props.hover,backgroundColor:props.background,speed:props.speed,dotLottieRefCallback:setDotLottie,style:{width:"100%",height:"100%"},renderConfig:// Auto-resize the canvas when controls are shown or hidden (causes a brief visible jump as the canvas resizes, but should be very rare)
props.controls?{autoResize:true}:undefined},src)}),props.controls?/*#__PURE__*/_jsx(LottieControls,{isVisible:isReady,initialIsVisible:isCanvas,dotLottie:dotLottie,direction:props.direction,loop:Boolean(props.loop),src:src}):null]});}DotLottie.defaultProps={srcUrl:placeholderUrl,autoplay:true,background:"#05F",controls:false,direction:1,hover:false,loop:true,speed:1};DotLottie.displayName="Dot Lottie";addPropertyControls(DotLottie,{srcType:{type:ControlType.Enum,displaySegmentedControl:true,title:"Source",options:["url","file"],optionTitles:["URL","File"]},srcUrl:{type:ControlType.String,title:"Link",placeholder:"../example.lottie",hidden:props=>props.srcType==="file"},srcFile:{type:ControlType.File,title:"File",allowedFileTypes:[".lottie",".json"],hidden:props=>props.srcType==="url"},autoplay:{type:ControlType.Boolean,title:"Autoplay",defaultValue:true},background:{type:ControlType.Color,title:"Backdrop",defaultValue:"#05F"},controls:{type:ControlType.Boolean,title:"Controls"},direction:{type:ControlType.Enum,title:"Direction",defaultValue:"1",displaySegmentedControl:true,segmentedControlDirection:"horizontal",options:["1","-1"],optionTitles:["Normal","Reverse"]},hover:{type:ControlType.Boolean,title:"Hover Play"},loop:{type:ControlType.Boolean,title:"Loop"},speed:{type:ControlType.Number,title:"Speed",defaultValue:1,min:1,max:10,unit:"x",step:.5,displayStepper:true},progress:{type:ControlType.Number,title:"Progress",defaultValue:0,min:0,max:100,step:1,description:"This component is made for Lottie files. [Learn more here](https://dotlottie.io/)."}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"DotLottie","slots":[],"annotations":{"framerDisableUnlink":"*","framerContractVersion":"1","framerIntrinsicHeight":"200","framerIntrinsicWidth":"200","framerSupportedLayoutWidth":"fixed","framerSupportedLayoutHeight":"any-prefer-fixed"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./DotLottie.map