import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{addPropertyControls,ControlType,motion}from"framer";import{containerStyles}from"https://framer.com/m/framer/default-utils.js@^0.45.0";import{useMemo}from"react";import{emptyStateStyle,stateParagraphStyle,stateTitleStyle}from"https://framer.com/m/framer/integrations-styles.js@0.2.0";const podcastsRegex=/^https?:\/\/podcasts\.apple\.com\/([^/]*)\/podcast(?:\/[^/]*)?\/id(\d+)(?:\?.*i=(\d+))?/;/**
 * APPLE PODCASTS
 *
 * @framerIntrinsicWidth 400
 * @framerIntrinsicHeight 175
 *
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight auto
 */ export default function ApplePodcasts({urlType,url,theme,style,...props}){const embedUrl=useMemo(()=>{var ref;const[,country,podcastId,episodeId]=(ref=url.match(podcastsRegex))!==null&&ref!==void 0?ref:[null,"","","",];if(!podcastId)return null;if(urlType==="episode"){return`https://embed.podcasts.apple.com/${country}/podcast/id${podcastId}?i=${episodeId}&theme=${theme}`;}else{return`https://embed.podcasts.apple.com/${country}/podcast/id${podcastId}?theme=${theme}`;}},[urlType,url,theme]);return(/*#__PURE__*/ _jsx(motion.div,{style:{...style,...containerStyles,placeContent:"center",placeItems:"center",overflow:"hidden"},...props,children:embedUrl?/*#__PURE__*/ _jsx("iframe",{src:embedUrl,width:"100%",height:"175px",frameBorder:"0",sandbox:"allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation-by-user-activation",allow:"autoplay *; encrypted-media *;"}):/*#__PURE__*/ _jsxs(motion.div,{style:{...emptyStateStyle,...style},children:[/*#__PURE__*/ _jsx("h1",{style:stateTitleStyle,children:"Apple Podcasts"}),/*#__PURE__*/ _jsx("p",{style:stateParagraphStyle,children:"Set a podcast URL in the Properties."})]})}));};addPropertyControls(ApplePodcasts,{urlType:{type:ControlType.Enum,title:"URL",options:["show","episode"],optionTitles:["Show","Episode"],displaySegmentedControl:true,defaultValue:"episode"},url:{type:ControlType.String,title:" ",placeholder:"https://podcasts.apple.com/us/podcast/***/***",defaultValue:"https://podcasts.apple.com/us/podcast/168-auto-goats-feat-koen-bok-and-jorn-van-dijk/id947191070?i=1000376864263"},theme:{type:ControlType.Enum,options:["light","dark"],optionTitles:["Light","Dark"],displaySegmentedControl:true}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"ApplePodcasts","slots":[],"annotations":{"framerIntrinsicWidth":"400","framerSupportedLayoutWidth":"fixed","framerSupportedLayoutHeight":"auto","framerIntrinsicHeight":"175","framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./ApplePodcasts.map