// Generated by Framer (1b27997)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/7k8KnPZGW9X4V3QNc1Hr/PSebSBlK24Nig1GOSeL6/kzUSIwReW.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/1GN424Yd6Y7lsvY8vOoN/2wMykwUV79mvqYdvWBhI/ZCD3JCImn.js";
const cycleOrder = [
  "fYE3joar9",
  "JhN58gTYJ",
  "rBPmIIcFr",
  "n_e6aymYg",
  "hYeVcoLPr",
  "m3tPLSGZt",
  "G_eW3lAFr",
  "HMHnIGaG8",
];
const serializationHash = "framer-LvFoh";
const variantClassNames = {
  fYE3joar9: "framer-v-1cmr48j",
  G_eW3lAFr: "framer-v-89k2xg",
  HMHnIGaG8: "framer-v-1hyuwya",
  hYeVcoLPr: "framer-v-mnds4l",
  JhN58gTYJ: "framer-v-yan00m",
  m3tPLSGZt: "framer-v-1iyzxdw",
  n_e6aymYg: "framer-v-1ejiaaf",
  rBPmIIcFr: "framer-v-1ksdzwk",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const transition1 = {
  delay: 0,
  duration: 0.6,
  ease: [0.75, 0.05, 0, 1.03],
  type: "tween",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Animation-Desktop": "n_e6aymYg",
  "Animation-Tablet": "HMHnIGaG8",
  "Branding-Desktop": "JhN58gTYJ",
  "Branding-Tablet": "m3tPLSGZt",
  "Framer-Desktop": "rBPmIIcFr",
  "Framer-Tablet": "G_eW3lAFr",
  "Ui/Ux-Desktop": "fYE3joar9",
  "Ui/Ux-Tablet": "hYeVcoLPr",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "fYE3joar9",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "fYE3joar9",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnterz2k0eo = activeVariantCallback(async (...args) => {
    setVariant("JhN58gTYJ");
  });
  const onMouseEnter1uv9jmq = activeVariantCallback(async (...args) => {
    setVariant("m3tPLSGZt");
  });
  const onMouseEnterkn1hgt = activeVariantCallback(async (...args) => {
    setVariant("fYE3joar9");
  });
  const onMouseEnter19wp529 = activeVariantCallback(async (...args) => {
    setVariant("hYeVcoLPr");
  });
  const onMouseEnterl0dzgy = activeVariantCallback(async (...args) => {
    setVariant("rBPmIIcFr");
  });
  const onMouseEnter1j3ivz6 = activeVariantCallback(async (...args) => {
    setVariant("G_eW3lAFr");
  });
  const onMouseEnter1xk537z = activeVariantCallback(async (...args) => {
    setVariant("n_e6aymYg");
  });
  const onMouseEnterlfxdtt = activeVariantCallback(async (...args) => {
    setVariant("HMHnIGaG8");
  });
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (
      ["hYeVcoLPr", "m3tPLSGZt", "G_eW3lAFr", "HMHnIGaG8"].includes(baseVariant)
    )
      return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1cmr48j",
            className,
            classNames,
          ),
          "data-framer-name": "Ui/Ux-Desktop",
          layoutDependency: layoutDependency,
          layoutId: "fYE3joar9",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              G_eW3lAFr: { "data-framer-name": "Framer-Tablet" },
              HMHnIGaG8: { "data-framer-name": "Animation-Tablet" },
              hYeVcoLPr: { "data-framer-name": "Ui/Ux-Tablet" },
              JhN58gTYJ: { "data-framer-name": "Branding-Desktop" },
              m3tPLSGZt: { "data-framer-name": "Branding-Tablet" },
              n_e6aymYg: { "data-framer-name": "Animation-Desktop" },
              rBPmIIcFr: { "data-framer-name": "Framer-Desktop" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-g41w2",
              "data-framer-name": "Content",
              layoutDependency: layoutDependency,
              layoutId: "ymodq_LJy",
              children: [
                /*#__PURE__*/ _jsx(Link, {
                  href: {
                    pathVariables: { zuPXbKjY1: "branding" },
                    unresolvedPathSlugs: {
                      zuPXbKjY1: {
                        collectionId: "UcWbpW2oX",
                        collectionItemId: "K3rIJmxHP",
                      },
                    },
                    webPageId: "WLs0OF8B2",
                  },
                  motionChild: true,
                  nodeId: "TUAmqvAap",
                  openInNewTab: false,
                  scopeId: "xf5I4_Lbn",
                  children: /*#__PURE__*/ _jsxs(motion.a, {
                    className: "framer-xo5sa1 framer-fnoon7",
                    "data-framer-name": "Point 1",
                    layoutDependency: layoutDependency,
                    layoutId: "TUAmqvAap",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h2, {
                            className: "framer-styles-preset-d6ofy9",
                            "data-styles-preset": "kzUSIwReW",
                            style: { "--framer-text-alignment": "center" },
                            children: "DEVELOPMENT",
                          }),
                        }),
                        className: "framer-1tt4h79",
                        "data-highlight": true,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "EW9iAynpC",
                        onMouseEnter: onMouseEnterz2k0eo,
                        style: {
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        variants: {
                          JhN58gTYJ: {
                            "--extracted-1of0zx5":
                              "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                          },
                          m3tPLSGZt: {
                            "--extracted-1of0zx5":
                              "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            G_eW3lAFr: { onMouseEnter: onMouseEnter1uv9jmq },
                            HMHnIGaG8: { onMouseEnter: onMouseEnter1uv9jmq },
                            hYeVcoLPr: { onMouseEnter: onMouseEnter1uv9jmq },
                            JhN58gTYJ: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-1of0zx5, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                  },
                                  children: "DEVELOPMENT",
                                }),
                              }),
                            },
                            m3tPLSGZt: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-1of0zx5, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                  },
                                  children: "DEVELOPMENT",
                                }),
                              }),
                              onMouseEnter: onMouseEnter1uv9jmq,
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1x9tv1g",
                        "data-framer-name": "Text",
                        layoutDependency: layoutDependency,
                        layoutId: "edm6R7Dto",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h0wt6i",
                                "data-styles-preset": "ZCD3JCImn",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                },
                                children: "Web & Mobile",
                              }),
                            }),
                            className: "framer-tpwd1f",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "bwot61Ens",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            variants: {
                              JhN58gTYJ: {
                                "--extracted-r6o4lv":
                                  "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              },
                              m3tPLSGZt: {
                                "--extracted-r6o4lv":
                                  "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              },
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                JhN58gTYJ: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                      },
                                      children: "Web & Mobile",
                                    }),
                                  }),
                                },
                                m3tPLSGZt: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                      },
                                      children: "Web & Mobile",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h0wt6i",
                                "data-styles-preset": "ZCD3JCImn",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                },
                                children: "Software Systems",
                              }),
                            }),
                            className: "framer-1ononas",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "fcqmBWLoe",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            variants: {
                              JhN58gTYJ: {
                                "--extracted-r6o4lv":
                                  "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              },
                              m3tPLSGZt: {
                                "--extracted-r6o4lv":
                                  "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              },
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                JhN58gTYJ: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                      },
                                      children: "Software Systems",
                                    }),
                                  }),
                                },
                                m3tPLSGZt: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                      },
                                      children: "Software Systems",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                        ],
                      }),
                    ],
                  }),
                }),
                /*#__PURE__*/ _jsx(Link, {
                  href: {
                    pathVariables: { zuPXbKjY1: "ui-ux" },
                    unresolvedPathSlugs: {
                      zuPXbKjY1: {
                        collectionId: "UcWbpW2oX",
                        collectionItemId: "g7KQ98Ym3",
                      },
                    },
                    webPageId: "WLs0OF8B2",
                  },
                  motionChild: true,
                  nodeId: "gj6cFR5gZ",
                  openInNewTab: false,
                  scopeId: "xf5I4_Lbn",
                  children: /*#__PURE__*/ _jsxs(motion.a, {
                    className: "framer-yeytro framer-fnoon7",
                    "data-framer-name": "Point 2",
                    layoutDependency: layoutDependency,
                    layoutId: "gj6cFR5gZ",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-m30v27",
                        "data-framer-name": "Text",
                        layoutDependency: layoutDependency,
                        layoutId: "AAi66Ejon",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h0wt6i",
                                "data-styles-preset": "ZCD3JCImn",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                },
                                children: "Machine Learning",
                              }),
                            }),
                            className: "framer-1ugcg9f",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "KoqVQpLRf",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            variants: {
                              G_eW3lAFr: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              HMHnIGaG8: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              JhN58gTYJ: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              m3tPLSGZt: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              n_e6aymYg: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              rBPmIIcFr: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                G_eW3lAFr: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Machine Learning",
                                    }),
                                  }),
                                },
                                HMHnIGaG8: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Machine Learning",
                                    }),
                                  }),
                                },
                                JhN58gTYJ: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Machine Learning",
                                    }),
                                  }),
                                },
                                m3tPLSGZt: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Machine Learning",
                                    }),
                                  }),
                                },
                                n_e6aymYg: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Machine Learning",
                                    }),
                                  }),
                                },
                                rBPmIIcFr: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Machine Learning",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h0wt6i",
                                "data-styles-preset": "ZCD3JCImn",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                },
                                children: "Intelligent Systems",
                              }),
                            }),
                            className: "framer-3at8g8",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "CeVXRlTQ_",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            variants: {
                              G_eW3lAFr: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              HMHnIGaG8: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              JhN58gTYJ: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              m3tPLSGZt: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              n_e6aymYg: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                              rBPmIIcFr: {
                                "--extracted-r6o4lv":
                                  "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              },
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                G_eW3lAFr: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Intelligent Systems",
                                    }),
                                  }),
                                },
                                HMHnIGaG8: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Intelligent Systems",
                                    }),
                                  }),
                                },
                                JhN58gTYJ: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Intelligent Systems",
                                    }),
                                  }),
                                },
                                m3tPLSGZt: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Intelligent Systems",
                                    }),
                                  }),
                                },
                                n_e6aymYg: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Intelligent Systems",
                                    }),
                                  }),
                                },
                                rBPmIIcFr: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                      },
                                      children: "Intelligent Systems",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h2, {
                            className: "framer-styles-preset-d6ofy9",
                            "data-styles-preset": "kzUSIwReW",
                            style: {
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-1of0zx5, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                            },
                            children: "AI/ML",
                          }),
                        }),
                        className: "framer-5lvxt2",
                        "data-highlight": true,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "xZyBh7cE_",
                        onMouseEnter: onMouseEnterkn1hgt,
                        style: {
                          "--extracted-1of0zx5":
                            "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            G_eW3lAFr: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                  },
                                  children: "AI/ML",
                                }),
                              }),
                              onMouseEnter: onMouseEnter19wp529,
                            },
                            HMHnIGaG8: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                  },
                                  children: "AI/ML",
                                }),
                              }),
                              onMouseEnter: onMouseEnter19wp529,
                            },
                            hYeVcoLPr: { onMouseEnter: onMouseEnter19wp529 },
                            JhN58gTYJ: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                  },
                                  children: "AI/ML",
                                }),
                              }),
                            },
                            m3tPLSGZt: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                  },
                                  children: "AI/ML",
                                }),
                              }),
                              onMouseEnter: onMouseEnter19wp529,
                            },
                            n_e6aymYg: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                  },
                                  children: "AI/ML",
                                }),
                              }),
                            },
                            rBPmIIcFr: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                  },
                                  children: "AI/ML",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                    ],
                  }),
                }),
                /*#__PURE__*/ _jsx(Link, {
                  href: {
                    pathVariables: { zuPXbKjY1: "framer" },
                    unresolvedPathSlugs: {
                      zuPXbKjY1: {
                        collectionId: "UcWbpW2oX",
                        collectionItemId: "lA6iLF0Ix",
                      },
                    },
                    webPageId: "WLs0OF8B2",
                  },
                  motionChild: true,
                  nodeId: "O3Al_bcfz",
                  openInNewTab: false,
                  scopeId: "xf5I4_Lbn",
                  children: /*#__PURE__*/ _jsxs(motion.a, {
                    className: "framer-c9wfz0 framer-fnoon7",
                    "data-framer-name": "Point 3",
                    layoutDependency: layoutDependency,
                    layoutId: "O3Al_bcfz",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h2, {
                            className: "framer-styles-preset-d6ofy9",
                            "data-styles-preset": "kzUSIwReW",
                            style: { "--framer-text-alignment": "center" },
                            children: "MECHATRONICS",
                          }),
                        }),
                        className: "framer-1kjpvta",
                        "data-highlight": true,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "uBz1EgfBw",
                        onMouseEnter: onMouseEnterl0dzgy,
                        style: {
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        variants: {
                          G_eW3lAFr: {
                            "--extracted-1of0zx5":
                              "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                          },
                          rBPmIIcFr: {
                            "--extracted-1of0zx5":
                              "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            G_eW3lAFr: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-1of0zx5, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                  },
                                  children: "MECHATRONICS",
                                }),
                              }),
                              onMouseEnter: onMouseEnter1j3ivz6,
                            },
                            HMHnIGaG8: { onMouseEnter: onMouseEnter1j3ivz6 },
                            hYeVcoLPr: { onMouseEnter: onMouseEnter1j3ivz6 },
                            m3tPLSGZt: { onMouseEnter: onMouseEnter1j3ivz6 },
                            rBPmIIcFr: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-1of0zx5, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                  },
                                  children: "MECHATRONICS",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-zku36l",
                        "data-framer-name": "Text",
                        layoutDependency: layoutDependency,
                        layoutId: "yPV7BkiXa",
                        children: /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-h0wt6i",
                              "data-styles-preset": "ZCD3JCImn",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                              },
                              children: "Robotics & Hardware",
                            }),
                          }),
                          className: "framer-1cr6g4y",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "KFvBDXiha",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          variants: {
                            G_eW3lAFr: {
                              "--extracted-r6o4lv":
                                "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                            },
                            rBPmIIcFr: {
                              "--extracted-r6o4lv":
                                "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                            },
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                          ...addPropertyOverrides(
                            {
                              G_eW3lAFr: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-h0wt6i",
                                    "data-styles-preset": "ZCD3JCImn",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                    },
                                    children: "Robotics & Hardware",
                                  }),
                                }),
                              },
                              rBPmIIcFr: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-h0wt6i",
                                    "data-styles-preset": "ZCD3JCImn",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                    },
                                    children: "Robotics & Hardware",
                                  }),
                                }),
                              },
                            },
                            baseVariant,
                            gestureVariant,
                          ),
                        }),
                      }),
                    ],
                  }),
                }),
                /*#__PURE__*/ _jsx(Link, {
                  href: {
                    pathVariables: { zuPXbKjY1: "animation" },
                    unresolvedPathSlugs: {
                      zuPXbKjY1: {
                        collectionId: "UcWbpW2oX",
                        collectionItemId: "wniEElUYE",
                      },
                    },
                    webPageId: "WLs0OF8B2",
                  },
                  motionChild: true,
                  nodeId: "rG5m7zvzX",
                  openInNewTab: false,
                  scopeId: "xf5I4_Lbn",
                  children: /*#__PURE__*/ _jsxs(motion.a, {
                    className: "framer-1e4s23v framer-fnoon7",
                    "data-framer-name": "Point 4",
                    layoutDependency: layoutDependency,
                    layoutId: "rG5m7zvzX",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1ccdnes",
                        "data-framer-name": "Text",
                        layoutDependency: layoutDependency,
                        layoutId: "ACOrI9ggR",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h0wt6i",
                                "data-styles-preset": "ZCD3JCImn",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                },
                                children: "Network Security",
                              }),
                            }),
                            className: "framer-1790xbs",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "V565qXzWZ",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            variants: {
                              HMHnIGaG8: {
                                "--extracted-r6o4lv":
                                  "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              },
                              n_e6aymYg: {
                                "--extracted-r6o4lv":
                                  "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              },
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                HMHnIGaG8: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                      },
                                      children: "Network Security",
                                    }),
                                  }),
                                },
                                n_e6aymYg: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                      },
                                      children: "Network Security",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h0wt6i",
                                "data-styles-preset": "ZCD3JCImn",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46)))",
                                },
                                children: "Infrastructure & Audits",
                              }),
                            }),
                            className: "framer-1qp6l38",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "HcbbctVaU",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-5777202a-0ea6-448f-b785-3c665721a4a8, rgb(46, 46, 46))",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            variants: {
                              HMHnIGaG8: {
                                "--extracted-r6o4lv":
                                  "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              },
                              n_e6aymYg: {
                                "--extracted-r6o4lv":
                                  "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                              },
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                HMHnIGaG8: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                      },
                                      children: "Infrastructure & Audits",
                                    }),
                                  }),
                                },
                                n_e6aymYg: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h0wt6i",
                                      "data-styles-preset": "ZCD3JCImn",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                      },
                                      children: "Infrastructure & Audits",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h2, {
                            className: "framer-styles-preset-d6ofy9",
                            "data-styles-preset": "kzUSIwReW",
                            style: { "--framer-text-alignment": "center" },
                            children: "CYBERSECURITY",
                          }),
                        }),
                        className: "framer-1nh6yap",
                        "data-highlight": true,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "yEBt0FCgx",
                        onMouseEnter: onMouseEnter1xk537z,
                        style: {
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        variants: {
                          HMHnIGaG8: {
                            "--extracted-1of0zx5":
                              "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                          },
                          n_e6aymYg: {
                            "--extracted-1of0zx5":
                              "var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255))",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            G_eW3lAFr: { onMouseEnter: onMouseEnterlfxdtt },
                            HMHnIGaG8: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-1of0zx5, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                  },
                                  children: "CYBERSECURITY",
                                }),
                              }),
                              onMouseEnter: onMouseEnterlfxdtt,
                            },
                            hYeVcoLPr: { onMouseEnter: onMouseEnterlfxdtt },
                            m3tPLSGZt: { onMouseEnter: onMouseEnterlfxdtt },
                            n_e6aymYg: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-d6ofy9",
                                  "data-styles-preset": "kzUSIwReW",
                                  style: {
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-1of0zx5, var(--token-d4ca82da-9858-4dad-acd0-b334826e1013, rgb(255, 255, 255)))",
                                  },
                                  children: "CYBERSECURITY",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                    ],
                  }),
                }),
                ,
              ],
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Image, {
                background: {
                  alt: "UI image",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) + 68,
                  ),
                  pixelHeight: 304,
                  pixelWidth: 440,
                  src: "https://framerusercontent.com/images/Te0KZO8vu8nZAiqQWZqQ1eMg.png",
                },
                className: "framer-vtz9m",
                "data-framer-name": "Image1",
                layoutDependency: layoutDependency,
                layoutId: "kadxibn70",
                ...addPropertyOverrides(
                  {
                    JhN58gTYJ: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 68,
                        ),
                        pixelHeight: 248,
                        pixelWidth: 360,
                        src: "https://framerusercontent.com/images/CC8McVzzO0R7udDOSECyPEPGsE0.png",
                      },
                    },
                    n_e6aymYg: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 389,
                        ),
                        pixelHeight: 386,
                        pixelWidth: 558,
                        sizes: "279px",
                        src: "https://framerusercontent.com/images/jJFlftiHE3hSOQ1JIc5El1MAQnw.png",
                        srcSet:
                          "https://framerusercontent.com/images/jJFlftiHE3hSOQ1JIc5El1MAQnw.png?scale-down-to=512 512w,https://framerusercontent.com/images/jJFlftiHE3hSOQ1JIc5El1MAQnw.png 558w",
                      },
                    },
                    rBPmIIcFr: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 141,
                        ),
                        pixelHeight: 386,
                        pixelWidth: 558,
                        sizes: "279px",
                        src: "https://framerusercontent.com/images/EprXwjKEBoRM8KRGGEcIr7YBDdw.png",
                        srcSet:
                          "https://framerusercontent.com/images/EprXwjKEBoRM8KRGGEcIr7YBDdw.png?scale-down-to=512 512w,https://framerusercontent.com/images/EprXwjKEBoRM8KRGGEcIr7YBDdw.png 558w",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Image, {
                background: {
                  alt: "UI image",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) + 366,
                  ),
                  pixelHeight: 304,
                  pixelWidth: 440,
                  src: "https://framerusercontent.com/images/Aqbu7kPIEdd41hwrARS5mPe8Ta8.png",
                },
                className: "framer-1a9jdw4",
                "data-framer-name": "Image2",
                layoutDependency: layoutDependency,
                layoutId: "ck_jEascr",
                ...addPropertyOverrides(
                  {
                    JhN58gTYJ: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 118,
                        ),
                        pixelHeight: 304,
                        pixelWidth: 440,
                        src: "https://framerusercontent.com/images/SqvXFHpY99P8W4osLxWdgK1w.png",
                      },
                    },
                    n_e6aymYg: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 294,
                        ),
                        pixelHeight: 248,
                        pixelWidth: 358,
                        src: "https://framerusercontent.com/images/mTFmtxmygqdvpVJYlTH4uXV2otA.png",
                      },
                    },
                    rBPmIIcFr: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 418,
                        ),
                        pixelHeight: 248,
                        pixelWidth: 358,
                        src: "https://framerusercontent.com/images/qD74yJN0mtCfqzLiyeeVdjj30.png",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Image, {
                background: {
                  alt: "UI image",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) + 238,
                  ),
                  pixelHeight: 248,
                  pixelWidth: 358,
                  src: "https://framerusercontent.com/images/aGsDjoLwW8jT2bmM2uK86UpTBKo.png",
                },
                className: "framer-1yrlmfy",
                "data-framer-name": "Image3",
                layoutDependency: layoutDependency,
                layoutId: "Dd3HQ8k70",
                ...addPropertyOverrides(
                  {
                    JhN58gTYJ: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 371,
                        ),
                        pixelHeight: 386,
                        pixelWidth: 558,
                        sizes: "279px",
                        src: "https://framerusercontent.com/images/AWyWbUhQemVzFi2HWkUsj8kuos4.png",
                        srcSet:
                          "https://framerusercontent.com/images/AWyWbUhQemVzFi2HWkUsj8kuos4.png?scale-down-to=512 512w,https://framerusercontent.com/images/AWyWbUhQemVzFi2HWkUsj8kuos4.png 558w",
                      },
                    },
                    n_e6aymYg: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 617,
                        ),
                        pixelHeight: 304,
                        pixelWidth: 440,
                        src: "https://framerusercontent.com/images/SjmtAi2v2tz7hZs4HMTJOr2NlXQ.png",
                      },
                    },
                    rBPmIIcFr: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 604,
                        ),
                        pixelHeight: 304,
                        pixelWidth: 440,
                        src: "https://framerusercontent.com/images/L28eSLKreJT4IFWi9VMzoc7TI.png",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Image, {
                background: {
                  alt: "UI image",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) +
                      (componentViewport?.height || 869) -
                      267,
                  ),
                  pixelHeight: 386,
                  pixelWidth: 558,
                  sizes: "279px",
                  src: "https://framerusercontent.com/images/Qy1hTtXWXmM1yNP30LPkmQ0q6Hc.png",
                  srcSet:
                    "https://framerusercontent.com/images/Qy1hTtXWXmM1yNP30LPkmQ0q6Hc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Qy1hTtXWXmM1yNP30LPkmQ0q6Hc.png 558w",
                },
                className: "framer-1mqtbpa",
                "data-framer-name": "Image4",
                layoutDependency: layoutDependency,
                layoutId: "uMX_981qJ",
                ...addPropertyOverrides(
                  {
                    JhN58gTYJ: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 225,
                        ),
                        pixelHeight: 248,
                        pixelWidth: 360,
                        src: "https://framerusercontent.com/images/xCsAD6OiFbRdZcIasNtRgmHqoZM.png",
                      },
                    },
                    n_e6aymYg: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 717,
                        ),
                        pixelHeight: 304,
                        pixelWidth: 440,
                        src: "https://framerusercontent.com/images/ZjZDRYMPHpxcGY3jymUBP8h2yBg.png",
                      },
                    },
                    rBPmIIcFr: {
                      background: {
                        alt: "UI image",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 258,
                        ),
                        pixelHeight: 248,
                        pixelWidth: 358,
                        src: "https://framerusercontent.com/images/mTFmtxmygqdvpVJYlTH4uXV2otA.png",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-412ujz",
                "data-framer-name": "Images",
                layoutDependency: layoutDependency,
                layoutId: "y0tzc7gYd",
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-LvFoh.framer-fnoon7, .framer-LvFoh .framer-fnoon7 { display: block; }",
  ".framer-LvFoh.framer-1cmr48j { align-content: center; align-items: center; cursor: default; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 170px 0px 227px 0px; position: relative; width: 1296px; }",
  ".framer-LvFoh .framer-g41w2 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 893px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-LvFoh .framer-xo5sa1, .framer-LvFoh .framer-c9wfz0 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 100%; }",
  ".framer-LvFoh .framer-1tt4h79, .framer-LvFoh .framer-5lvxt2, .framer-LvFoh .framer-1kjpvta, .framer-LvFoh .framer-1nh6yap { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
  ".framer-LvFoh .framer-1x9tv1g, .framer-LvFoh .framer-m30v27, .framer-LvFoh .framer-zku36l, .framer-LvFoh .framer-1ccdnes { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-LvFoh .framer-tpwd1f, .framer-LvFoh .framer-1ononas, .framer-LvFoh .framer-1ugcg9f, .framer-LvFoh .framer-3at8g8, .framer-LvFoh .framer-1cr6g4y, .framer-LvFoh .framer-1790xbs, .framer-LvFoh .framer-1qp6l38 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-LvFoh .framer-yeytro { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 100%; }",
  ".framer-LvFoh .framer-1e4s23v { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 100%; }",
  ".framer-LvFoh .framer-vtz9m { flex: none; height: 152px; left: 220px; overflow: hidden; position: absolute; top: 68px; width: 220px; z-index: 1; }",
  ".framer-LvFoh .framer-1a9jdw4 { flex: none; height: 152px; left: 0px; overflow: hidden; position: absolute; top: 366px; width: 220px; z-index: 1; }",
  ".framer-LvFoh .framer-1yrlmfy { flex: none; height: 124px; overflow: hidden; position: absolute; right: 127px; top: 238px; width: 179px; z-index: 1; }",
  ".framer-LvFoh .framer-1mqtbpa { bottom: 74px; flex: none; height: 193px; left: calc(49.30555555555558% - 279px / 2); overflow: hidden; position: absolute; width: 279px; z-index: 1; }",
  ".framer-LvFoh .framer-412ujz { align-content: center; align-items: center; aspect-ratio: 1.607977991746905 / 1; bottom: 74px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: hidden; padding: 0px; position: absolute; top: 68px; width: var(--framer-aspect-ratio-supported, 1169px); z-index: 0; }",
  ".framer-LvFoh.framer-v-yan00m .framer-g41w2, .framer-LvFoh.framer-v-mnds4l .framer-5lvxt2, .framer-LvFoh.framer-v-mnds4l .framer-1nh6yap, .framer-LvFoh.framer-v-1iyzxdw .framer-5lvxt2, .framer-LvFoh.framer-v-1iyzxdw .framer-1nh6yap, .framer-LvFoh.framer-v-89k2xg .framer-5lvxt2, .framer-LvFoh.framer-v-89k2xg .framer-1nh6yap, .framer-LvFoh.framer-v-1hyuwya .framer-5lvxt2, .framer-LvFoh.framer-v-1hyuwya .framer-1nh6yap { order: 0; }",
  ".framer-LvFoh.framer-v-yan00m .framer-vtz9m { height: 124px; left: unset; order: 1; right: 456px; width: 180px; }",
  ".framer-LvFoh.framer-v-yan00m .framer-1a9jdw4 { order: 2; top: 118px; }",
  ".framer-LvFoh.framer-v-yan00m .framer-1yrlmfy { height: 193px; left: 110px; order: 3; right: unset; top: 371px; width: 279px; }",
  ".framer-LvFoh.framer-v-yan00m .framer-1mqtbpa { bottom: unset; height: 124px; left: unset; order: 4; right: 0px; top: 225px; width: 180px; }",
  ".framer-LvFoh.framer-v-yan00m .framer-412ujz { aspect-ratio: unset; bottom: 305px; left: unset; order: 5; right: 0px; top: 0px; width: 1296px; }",
  ".framer-LvFoh.framer-v-1ksdzwk .framer-vtz9m { height: 193px; left: unset; right: 308px; top: 141px; width: 279px; }",
  ".framer-LvFoh.framer-v-1ksdzwk .framer-1a9jdw4 { bottom: 327px; height: unset; left: calc(6.867283950617306% - 179px / 2); top: 418px; width: 179px; }",
  ".framer-LvFoh.framer-v-1ksdzwk .framer-1yrlmfy { height: 152px; right: 660px; top: 604px; width: 220px; }",
  ".framer-LvFoh.framer-v-1ksdzwk .framer-1mqtbpa { bottom: unset; height: 124px; left: unset; right: 39px; top: 258px; width: 179px; }",
  ".framer-LvFoh.framer-v-1ksdzwk .framer-412ujz, .framer-LvFoh.framer-v-1ejiaaf .framer-412ujz { aspect-ratio: unset; bottom: 305px; left: unset; right: 0px; top: 0px; width: 1296px; }",
  ".framer-LvFoh.framer-v-1ejiaaf .framer-vtz9m { height: 193px; left: unset; right: 0px; top: 389px; width: 279px; }",
  ".framer-LvFoh.framer-v-1ejiaaf .framer-1a9jdw4 { bottom: 451px; height: unset; left: calc(30.47839506172842% - 179px / 2); top: 294px; width: 179px; }",
  ".framer-LvFoh.framer-v-1ejiaaf .framer-1yrlmfy { height: 152px; right: 1076px; top: 617px; width: 220px; }",
  ".framer-LvFoh.framer-v-1ejiaaf .framer-1mqtbpa { bottom: 0px; height: unset; left: calc(76.3888888888889% - 220px / 2); top: 717px; width: 220px; }",
  ".framer-LvFoh.framer-v-mnds4l.framer-1cmr48j, .framer-LvFoh.framer-v-1iyzxdw.framer-1cmr48j, .framer-LvFoh.framer-v-89k2xg.framer-1cmr48j, .framer-LvFoh.framer-v-1hyuwya.framer-1cmr48j { padding: 50px 0px 50px 0px; width: 810px; }",
  ".framer-LvFoh.framer-v-mnds4l .framer-xo5sa1, .framer-LvFoh.framer-v-mnds4l .framer-yeytro, .framer-LvFoh.framer-v-mnds4l .framer-c9wfz0, .framer-LvFoh.framer-v-1iyzxdw .framer-xo5sa1, .framer-LvFoh.framer-v-1iyzxdw .framer-yeytro, .framer-LvFoh.framer-v-1iyzxdw .framer-c9wfz0, .framer-LvFoh.framer-v-89k2xg .framer-xo5sa1, .framer-LvFoh.framer-v-89k2xg .framer-yeytro, .framer-LvFoh.framer-v-89k2xg .framer-c9wfz0, .framer-LvFoh.framer-v-1hyuwya .framer-xo5sa1, .framer-LvFoh.framer-v-1hyuwya .framer-yeytro, .framer-LvFoh.framer-v-1hyuwya .framer-c9wfz0 { flex-direction: column; justify-content: flex-start; }",
  ".framer-LvFoh.framer-v-mnds4l .framer-m30v27, .framer-LvFoh.framer-v-mnds4l .framer-1ccdnes, .framer-LvFoh.framer-v-1iyzxdw .framer-m30v27, .framer-LvFoh.framer-v-1iyzxdw .framer-1ccdnes, .framer-LvFoh.framer-v-89k2xg .framer-m30v27, .framer-LvFoh.framer-v-89k2xg .framer-1ccdnes, .framer-LvFoh.framer-v-1hyuwya .framer-m30v27, .framer-LvFoh.framer-v-1hyuwya .framer-1ccdnes { order: 1; }",
  ".framer-LvFoh.framer-v-mnds4l .framer-1e4s23v, .framer-LvFoh.framer-v-1iyzxdw .framer-1e4s23v, .framer-LvFoh.framer-v-89k2xg .framer-1e4s23v, .framer-LvFoh.framer-v-1hyuwya .framer-1e4s23v { flex-direction: column; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 869
 * @framerIntrinsicWidth 1296
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"JhN58gTYJ":{"layout":["fixed","auto"]},"rBPmIIcFr":{"layout":["fixed","auto"]},"n_e6aymYg":{"layout":["fixed","auto"]},"hYeVcoLPr":{"layout":["fixed","auto"]},"m3tPLSGZt":{"layout":["fixed","auto"]},"G_eW3lAFr":{"layout":["fixed","auto"]},"HMHnIGaG8":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerxf5I4_Lbn = withCSS(Component, css, "framer-LvFoh");
export default Framerxf5I4_Lbn;
Framerxf5I4_Lbn.displayName = "Home Service Card";
Framerxf5I4_Lbn.defaultProps = { height: 869, width: 1296 };
addPropertyControls(Framerxf5I4_Lbn, {
  variant: {
    options: [
      "fYE3joar9",
      "JhN58gTYJ",
      "rBPmIIcFr",
      "n_e6aymYg",
      "hYeVcoLPr",
      "m3tPLSGZt",
      "G_eW3lAFr",
      "HMHnIGaG8",
    ],
    optionTitles: [
      "Ui/Ux-Desktop",
      "Branding-Desktop",
      "Framer-Desktop",
      "Animation-Desktop",
      "Ui/Ux-Tablet",
      "Branding-Tablet",
      "Framer-Tablet",
      "Animation-Tablet",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  Framerxf5I4_Lbn,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framerxf5I4_Lbn",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerIntrinsicWidth: "1296",
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"JhN58gTYJ":{"layout":["fixed","auto"]},"rBPmIIcFr":{"layout":["fixed","auto"]},"n_e6aymYg":{"layout":["fixed","auto"]},"hYeVcoLPr":{"layout":["fixed","auto"]},"m3tPLSGZt":{"layout":["fixed","auto"]},"G_eW3lAFr":{"layout":["fixed","auto"]},"HMHnIGaG8":{"layout":["fixed","auto"]}}}',
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "869",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
